name: Publish to developer.z-wave.me

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Publish to developer.z-wave.me
      run: |
        cd ../ && ${MODULE_NAME}/.github/workflows/uploadModule.sh ${MODULE_ID} ${MODULE_NAME} ${USERNAME} ${PASSWORD} ${ADMIN}
      env:
        USERNAME: ${{secrets.DEVELOPER_ZWAVE_ME_USERNAME}}
        PASSWORD: ${{secrets.DEVELOPER_ZWAVE_ME_PASSWORD}}
        MODULE_NAME: ${{vars.MODULE_NAME}}
        MODULE_ID: ${{vars.MODULE_ID}}
        ADMIN: ${{vars.ADMIN}}
